#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install support for D.R.A.W.S.
  hosts: all
  gather_facts: no
  tasks:

  - name: Insert boot config configuration for D.R.A.W.S. / UDRC
    become: yes
    blockinfile:
      dest: /boot/config.txt
      create: yes
      block: |
        # Uncomment these if you have a D.R.A.W.S. / UDRC from NW Digital Radio
        # Flush all overlays, ie. deprecated overlays loaded from eeprom
        # dtoverlay=
        # Enable UDRC/DRAWS if no EEPROM
        # dtoverlay=draws,alsaname=udrc
        # https://www.raspberrypi.org/documentation/configuration/config-txt/overclocking.md
        force_turbo=1
        # Enable audio (loads snd_bcm2835)
        # dtparam=audio=0
        # End of D.R.A.W.S. / UDRC section

  - name: Create directory hamradio
    file:
      path: /home/pi/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - scons
      - asciidoctor
#      - libgps-dev # This isn't allowing compiles to complete yet
      - libudev-dev
      - nodejs
      - npm
      - lm-sensors
      - libasound2-dev

  - name: Insert sensors configuration for D.R.A.W.S. / UDRC
    become: yes
    blockinfile:
      dest: /etc/sensors.d/draws
      create: yes
      block: |
        # This is for the D.R.A.W.S. / UDRC from NW Digital Radio

        chip "ads1015-*"
                label in3 "User ADC Differential"
                label in4 "+12V"
                label in6 "User ADC 1"
                label in7 "User ADC 2"
                compute in4 ((48.7/10)+1)*@, @/((48.7/10)+1)

        # End of D.R.A.W.S. / UDRC section

#
# Install D.R.A.W.S. compatible version of GPSd
#
  - name: Git clone latest GPSd sources
    git:
      repo: https://gitlab.com/gpsd/gpsd.git
      dest: /home/pi/hamradio/gpsd

  - name: Build GPSd sources
    shell: scons
    args:
      chdir: /home/pi/hamradio/gpsd

  - name: Install GPSd
    become: yes
    shell: scons udev-install
    args:
      chdir: /home/pi/hamradio/gpsd

  - name: Remove GPSd build directory
    file:
      path: /home/pi/hamradio/gpsd
      state: absent

#  - name: Fix a troublesome gpsd config entry
#    become: yes
#    lineinfile:
#      path: /etc/default/gpsd
#      regexp: '^USBAUTO=\"true\"'
#      line: USBAUTO="false"

#  - name: Add D.R.A.W.S. port to gpsd config
#    become: yes
#    lineinfile:
#      path: /etc/default/gpsd
#      regexp: '^DEVICES=\"\"'
#      line: DEVICES="/dev/ttySC0 /dev/pps0"

#  - name: Add D.R.A.W.S. gps option to gpsd config
#    become: yes
#    lineinfile:
#      path: /etc/default/gpsd
#      regexp: '^GPSD_OPTIONS=\"\"'
#      line: GPSD_OPTIONS="-n"

#
# Install D.R.A.W.S. compatible version of Direwolf
#
  - name: Git clone latest Direwolf sources
    git:
      repo: https://www.github.com/wb2osz/direwolf
      dest: /home/pi/hamradio/direwolf

  - name: Checkout Dev Direwolf sources
    shell: git checkout dev
    args:
      chdir: /home/pi/hamradio/direwolf

  - name: Fix check for D.R.A.W.S. support
    lineinfile:
      path: /home/pi/hamradio/direwolf/src/dwgpsd.c
      regexp: '^#if GPSD_API_MAJOR_VERSION \< 5 \|\| GPSD_API_MAJOR_VERSION \> 8'
      line: '#if GPSD_API_MAJOR_VERSION < 5 || GPSD_API_MAJOR_VERSION > 10'

  - name: Create directory direwolf/build
    file:
      path: /home/pi/hamradio/direwolf/build
      state: directory

  - name: Build Dev Direwolf CMakeFiles
    command: cmake ..
    args:
      chdir: /home/pi/hamradio/direwolf/build

  - name: Build Dev Direwolf
    command: make
    args:
      chdir: /home/pi/hamradio/direwolf/build

  - name: Install Dev Direwolf
    become: yes
    command: make install
    args:
      chdir: /home/pi/hamradio/direwolf/build

  - name: Install-conf Dev Direwolf
    become: yes
    command: make install-conf
    args:
      chdir: /home/pi/hamradio/direwolf/build

  - name: Remove Dev Direwolf build directory
    file:
      path: /home/pi/hamradio/direwolf
      state: absent

#
# Install D.R.A.W.S. Manager
#
  - name: Update npm
    become: yes
    shell: npm install -g npm

  - name: Git clone latest DRAWS Manager sources
    git:
      repo: https://github.com/nwdigitalradio/draws-manager.git
      dest: /home/pi/hamradio/draws-manager

  - name: Install DRAWS Manager service file
    become: yes
    shell: cp draws-manager.service /lib/systemd/system
    args:
      chdir: /home/pi/hamradio/draws-manager

  - name: Install DRAWS Manager config file
    become: yes
    shell: cp draws-manager /etc/default
    args:
      chdir: /home/pi/hamradio/draws-manager

  - name: Install DRAWS-Manager webapp
    become: yes
    shell: /usr/bin/npm install
    args:
      chdir: /home/pi/hamradio/draws-manager/webapp

  - name: Add Northwest Digital Documentation to Desktop
    copy:
      src: "{{ playbook_dir }}/../files/home/pi/Desktop/Activating your DRAWS™ HAT.pdf"
      dest: "/home/pi/Desktop/Activating your DRAWS™ HAT.pdf"
