#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyMultiSDR
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Download latest SoapyMultiSDR sources
    git:
      repo: https://github.com/pothosware/SoapyMultiSDR.git
      dest: /home/{{ ham_user }}/hamradio/SoapyMultiSDR
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory SoapyMultiSDR/build
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyMultiSDR/build
      state: directory

  - name: Build SoapyMultiSDR CMakeFiles
    command: cmake --prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyMultiSDR/build

  - name: Build SoapyMultiSDR
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyMultiSDR/build

  - name: Install SoapyMultiSDR
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyMultiSDR/build

  - name: Remove SoapyMultiSDR build directory
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyMultiSDR
      state: absent
