#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install sparksdr
  hosts: all
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Determine latest version of sparksdr on web
    shell: curl --silent "http://www.ihopper.org/radio/sparksdr2.htm" | grep -Po "http://www.ihopper.org/radio/download.aspx\?file=sparksdr[0-9]+_[0-9]+_[0-9]+_[0-9]+_linux.tar.gz" | grep -Po "[0-9]+_[0-9]+_[0-9]+_[0-9]+"
    args:
      warn: no
    register: sparksdr_version

  - name: Download and Unarchive sparksdr {{ sparksdr_version.stdout }}
    become: yes
    unarchive:
      src: "http://www.ihopper.org/radio/download.aspx?file=sparksdr{{ sparksdr_version.stdout }}_linux.tar.gz"
      dest: "/usr/local/"
      remote_src: yes
