#
# Copyright 2020 - 2021, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install HackRF
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - gr-osmosdr
      - libfftw3-dev
      - libusb-1.0-0-dev

  - name: Download latest HackRF sources
    git:
      repo: https://github.com/mossmann/hackrf.git
      dest: /home/{{ ham_user }}/hamradio/hackrf

  - name: Create directory hackrf/host/build
    file:
      path: /home/{{ ham_user }}/hamradio/hackrf/host/build
      state: directory

  - name: Build HackRF CMakeFiles
    command: cmake ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/hackrf/host/build

  - name: Build HackRF
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/hackrf/host/build

  - name: Install HackRF
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/hackrf/host/build

  - name: Remove HackRF build directory
    file:
      path: /home/{{ ham_user }}/hamradio/hackrf
      state: absent

  - name: Configure dynamic linker run-time bindings
    become: yes
    command: ldconfig

  - name: Download latest SoapyHackRF sources
    git:
      repo: https://github.com/pothosware/SoapyHackRF.git
      dest: /home/{{ ham_user }}/hamradio/SoapyHackRF

  - name: Create directory SoapyHackRF/build
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyHackRF/build
      state: directory

  - name: Build SoapyHackRF CMakeFiles
    command: cmake ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyHackRF/build

  - name: Build SoapyHackRF
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyHackRF/build

  - name: Install SoapyHackRF
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyHackRF/build

  - name: Remove SoapyHackRF build directory
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyHackRF
      state: absent
