#
# Copyright 2021, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install RBNC - Client for reverse beacon network
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - git
      - libusb-1.0-0-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtpositioning5-dev
      - libqt5serialport5-dev
      - qtmultimedia5-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Git clone latest RBNC sources
    git:
      repo: https://github.com/hmatuschek/skcc
      dest: /home/{{ ham_user }}/hamradio/skcc
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory skcc/build
    file:
      path: /home/{{ ham_user }}/hamradio/skcc/build
      state: directory

  - name: Build RBNC Makefiles
    command: cmake .. -Wno-dev
    args:
      chdir: /home/{{ ham_user }}/hamradio/skcc/build

  - name: Build RBNC
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/skcc/build

  - name: Install RBNC
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/skcc/build

  - name: Modify categories for rbnc.desktop
    become: yes
    lineinfile:
      path: /usr/local/share/applications/rbnc.desktop
      regexp: '^Categories=HamRadio;Network'
      line: Categories=HamRadio

  - name: Modify icon path for rbnc.desktop
    become: yes
    lineinfile:
      path: /usr/local/share/applications/rbnc.desktop
      regexp: '^Icon=rbnc'
      line: Icon=/usr/local/share/icons/hicolor/64x64/apps/rbnc.png 

  - name: Remove RBNC
    file:
      path: /home/{{ ham_user }}/hamradio/skcc
      state: absent
