#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyVOLKConverters
  hosts: all
  environment:
    # Build-Time Tuning:
    # These only work for ARM32, not ARM64:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - gr-osmosdr
      - libfftw3-dev
      - libusb-1.0-0-dev
      - python3
      - python3-pip
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent python3 modules
    become: yes
    shell: pip3 install mako
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download latest volk sources
    git:
      repo: https://github.com/gnuradio/volk
      dest: /home/{{ ham_user }}/hamradio/volk
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory volk/build
    file:
      path: /home/{{ ham_user }}/hamradio/volk/build
      state: directory

#
# need "cmake .." for ARMv8
#

  - name: Build volk CMakeFiles (ARM)
    command: cmake --prefix=/usr -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/arm_cortex_a72_hardfp_native.cmake ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/volk/build
    when: is_arm|bool

  - name: Build volk CMakeFiles (x86)
    command: cmake --prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/volk/build
    when: is_i386|bool or is_x86_64|bool

  - name: Build volk
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/volk/build

  - name: Install volk
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/volk/build

  - name: Remove volk build directory
    file:
      path: /home/{{ ham_user }}/hamradio/volk
      state: absent

  - name: Download latest SoapyVOLKConverters sources
    git:
      repo: https://github.com/pothosware/SoapyVOLKConverters
      dest: /home/{{ ham_user }}/hamradio/SoapyVOLKConverters
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory SoapyVOLKConverters/build
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyVOLKConverters/build
      state: directory

  - name: Build SoapyVOLKConverters CMakeFiles
    command: cmake --prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyVOLKConverters/build

  - name: Build SoapyVOLKConverters
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyVOLKConverters/build

  - name: Install SoapyVOLKConverters
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyVOLKConverters/build

  - name: Remove SoapyVOLKConverters build directory
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyVOLKConverters
      state: absent
