#
# Copyright 2020 - 2021, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyRemote
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Download latest SoapyRemote sources
    git:
      repo: https://github.com/pothosware/SoapyRemote.git
      dest: /home/{{ ham_user }}/hamradio/SoapyRemote
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory SoapyRemote/build
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyRemote/build
      state: directory

  - name: Build SoapyRemote CMakeFiles
    command: cmake ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyRemote/build

  - name: Build SoapyRemote
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyRemote/build

  - name: Install SoapyRemote
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyRemote/build

  - name: Remove SoapyRemote build directory
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyRemote
      state: absent
