#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install QSSTV
  hosts: all
  gather_facts: no
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - g++
      - libfftw3-dev
      - libpulse-dev
      - libhamlib-dev
      - libasound2-dev
      - libv4l-dev
      - libopenjp2-7
      - libopenjp2-7-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (Raspberry Pi Buster)
    become: yes
    package:
      name: qt5-default
      state: present
    when: is_rpi|bool and is_buster|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download QSSTV sources
    git:
      repo: https://github.com/ON4QZ/QSSTV.git
      dest: /home/{{ ham_user }}/hamradio/qsstv
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Build QSSTV Makefile
    command: qmake
    args:
      chdir: /home/{{ ham_user }}/hamradio/qsstv/src

  - name: Build QSSTV
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/qsstv/src

  - name: Install QSSTV
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/qsstv/src

  - name: Modify categories for qsstv.desktop
    lineinfile:
      path: "/home/{{ ham_user }}/hamradio/qsstv/qsstv.desktop"
      regexp: '^Categories=.*'
      line: Categories=HamRadio

  - name: Copy qsstv.desktop to /usr/local/share/applications
    become: yes
    copy:
      src: "/home/{{ ham_user }}/hamradio/qsstv/qsstv.desktop"
      dest: /usr/local/share/applications/qsstv.desktop
      remote_src: yes

  - name: Remove QSSTV build directory
    file:
      path: /home/{{ ham_user }}/hamradio/qsstv
      state: absent
