#
# Copyright 2020 - 2022, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install TAPR WSPR Packages
  hosts: all
  tasks:

  - name: Install dependent packages (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - g++
      - make
      - grep
      - mawk
      - ntp
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent packages (ARM Buster)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python-setuptools
      - python-pil
    when: is_arm|bool and is_buster|bool

  - name: Install dependent packages (ARM Bullseye)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3-setuptools
      - python3-pil.imagetk
    when: is_arm|bool and is_bullseye|bool

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

#
# WsprryPi
#

# Submitted bug reports upstream; using basic (original) WsprryPi for now.
# - djs 2020-06-07
#
#  - name: Clone WsprryPi source
#    git:
#      repo: https://github.com/JamesP6000/WsprryPi.git
#      dest: /home/{{ ham_user }}/hamradio/WsprryPi
#    retries: 5
#    delay: 30
#    register: result
#    until: result.failed == false
#
#  - name: Build WsprryPi
#    command: make
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/WsprryPi
#
#  - name: Install WsprryPi
#    become: yes
#    command: make install
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/WsprryPi
#
#  - name: Remove WsprryPi build directory
#    file:
#      path: /home/{{ ham_user }}/hamradio/WsprryPi
#      state: absent

  - name: Clone WsprryPi source
    git:
      repo: https://github.com/DanAnkers/WsprryPi.git
      dest: /home/{{ ham_user }}/hamradio/WsprryPi
    when: is_hampi|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Build WsprryPi
    command: gcc wspr.c -o wspr-pi
    args:
      chdir: /home/{{ ham_user }}/hamradio/WsprryPi
    when: is_hampi|bool

  - name: Install WsprryPi
    become: yes
    command: install wspr-pi /usr/bin
    args:
      chdir: /home/{{ ham_user }}/hamradio/WsprryPi
    when: is_hampi|bool

  - name: Remove WsprryPi build directory
    file:
      path: /home/{{ ham_user }}/hamradio/WsprryPi
      state: absent
    when: is_hampi|bool


#
# PiCW
#

#  - name: Clone PiCW source
#    git:
#      repo: https://github.com/JamesP6000/PiCW.git
#      dest: /home/{{ ham_user }}/hamradio/PiCW
#    retries: 5
#    delay: 30
#    register: result
#    until: result.failed == false
#
#  - name: Build PiCW
#    command: make
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/PiCW
#
#  - name: Install PiCW
#    become: yes
#    command: make install
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/PiCW
#
#  - name: Remove PiCW build directory
#    file:
#      path: /home/{{ ham_user }}/hamradio/PiCW
#      state: absent


#
# Freq_Pi
#

#  - name: Clone Freq_Pi
#    git:
#      repo: https://github.com/JennyList/LanguageSpy/blob/master/RaspberryPi/rf/freq_pi/freq_pi.c
#      dest: /home/{{ ham_user }}/hamradio
#    retries: 5
#    delay: 30
#    register: result
#    until: result.failed == false

#
# PySSTV
#

  - name: Install dependent packages
    become: yes
    package:
      name: python3-pip
      state: present
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: pip3 install setuptools
    become: yes
    command: "pip3 install setuptools --upgrade --no-binary :all:"
    args:
      chdir: /home/{{ ham_user }}/hamradio
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: pip3 install PySSTV
    become: yes
    command: pip3 install PySSTV
    args:
      chdir: /home/{{ ham_user }}/hamradio
    retries: 5
    delay: 30
    register: result
    until: result.failed == false
