#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install QDMR - GUI application and command line tool to program DMR radios
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - git
      - libusb-1.0-0-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtpositioning5-dev
      - libqt5serialport5-dev
      - libyaml-cpp-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libyaml-cpp0.6
    when: not is_jammy|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Install dependent libraries (Jammy)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libyaml-cpp0.7
    when: is_jammy|bool
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Git clone latest QDMR sources
    git:
      repo: https://github.com/hmatuschek/qdmr
      dest: /home/{{ ham_user }}/hamradio/qdmr
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory qdmr/build
    file:
      path: /home/{{ ham_user }}/hamradio/qdmr/build
      state: directory

  - name: Build QDMR Makefiles
    command: cmake --install-prefix=/usr .. -Wno-dev
    args:
      chdir: /home/{{ ham_user }}/hamradio/qdmr/build

  - name: Build QDMR
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/qdmr/build

  - name: Install QDMR
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/qdmr/build

  - name: Run udevadm to activate new USB rule file
    become: yes
    command: udevadm control --reload-rules

  - name: Modify categories for qdmr.desktop
    become: yes
    lineinfile:
      path: /usr/local/share/applications/qdmr.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio

  - name: Modify icon path for qdmr.desktop
    become: yes
    lineinfile:
      path: /usr/local/share/applications/qdmr.desktop
      regexp: '^Icon=qdmr'
      line: Icon=/usr/share/icons/hicolor/64x64/qdmr.png 

  - name: Remove QDMR
    file:
      path: /home/{{ ham_user }}/hamradio/qdmr
      state: absent
