#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyAudio
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Download latest SoapyAudio sources
    git:
      repo: https://github.com/pothosware/SoapyAudio.git
      dest: /home/{{ ham_user }}/hamradio/SoapyAudio
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory SoapyAudio/build
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyAudio/build
      state: directory

  - name: Build SoapyAudio CMakeFiles
    command: cmake --prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyAudio/build

  - name: Build SoapyAudio
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyAudio/build

  - name: Install SoapyAudio
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyAudio/build

  - name: Remove SoapyAudio build directory
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyAudio
      state: absent
