#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install TAPR WSPR Packages
  hosts: all
  tasks:

  - name: Install dependent packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - g++
      - make
      - grep
      - mawk
      - ntp
      - python-setuptools
      - python-pil

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

#
# WsprryPi
#

# Submitted bug reports upstream; using basic (original) WsprryPi for now.
# - djs 2020-06-07
#
#  - name: Clone WsprryPi source
#    git:
#      repo: https://github.com/JamesP6000/WsprryPi.git
#      dest: /home/{{ ham_user }}/hamradio/WsprryPi
#
#  - name: Build WsprryPi
#    command: make
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/WsprryPi
#
#  - name: Install WsprryPi
#    become: yes
#    command: make install
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/WsprryPi
#
#  - name: Remove WsprryPi build directory
#    file:
#      path: /home/{{ ham_user }}/hamradio/WsprryPi
#      state: absent

  - name: Clone WsprryPi source
    git:
      repo: https://github.com/DanAnkers/WsprryPi.git
      dest: /home/{{ ham_user }}/hamradio/WsprryPi

  - name: Build WsprryPi
    command: gcc wspr.c -o wspr-pi
    args:
      chdir: /home/{{ ham_user }}/hamradio/WsprryPi

  - name: Install WsprryPi
    become: yes
    command: install wspr-pi /usr/local/bin
    args:
      chdir: /home/{{ ham_user }}/hamradio/WsprryPi

  - name: Remove WsprryPi build directory
    file:
      path: /home/{{ ham_user }}/hamradio/WsprryPi
      state: absent


#
# PiCW
#

#  - name: Clone PiCW source
#    git:
#      repo: https://github.com/JamesP6000/PiCW.git
#      dest: /home/{{ ham_user }}/hamradio/PiCW
#
#  - name: Build PiCW
#    command: make
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/PiCW
#
#  - name: Install PiCW
#    become: yes
#    command: make install
#    args:
#      chdir: /home/{{ ham_user }}/hamradio/PiCW
#
#  - name: Remove PiCW build directory
#    file:
#      path: /home/{{ ham_user }}/hamradio/PiCW
#      state: absent


#
# Freq_Pi
#

#  - name: Clone Freq_Pi
#    git:
#      repo: https://github.com/JennyList/LanguageSpy/blob/master/RaspberryPi/rf/freq_pi/freq_pi.c
#      dest: /home/{{ ham_user }}/hamradio

#
# PySSTV
#

  - name: Install dependent packages
    become: yes
    package:
      name: python-pip
      state: present

  - name: pip install setuptools
    become: yes
    command: "pip install setuptools --upgrade --no-binary :all:"
    args:
      chdir: /home/{{ ham_user }}/hamradio

  - name: pip install PySSTV
    become: yes
    command: pip install PySSTV
    args:
      chdir: /home/{{ ham_user }}/hamradio
