#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyRTLSDR
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: libusb-1.0-0-dev
      state: present
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download latest RTL-SDR sources
    git:
      repo: https://github.com/steve-m/librtlsdr
      dest: /home/{{ ham_user }}/hamradio/librtlsdr
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory librtlsdr/build
    file:
      path: /home/{{ ham_user }}/hamradio/librtlsdr/build
      state: directory

  - name: Build RTL-SDR CMakeFiles
    command: cmake --prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/librtlsdr/build

  - name: Build RTL-SDR
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/librtlsdr/build

  - name: Install RTL-SDR
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/librtlsdr/build

  - name: Remove RTL-SDR build directory
    file:
      path: /home/{{ ham_user }}/hamradio/librtlsdr
      state: absent

  - name: Download latest SoapyRTLSDR sources
    git:
      repo: https://github.com/pothosware/SoapyRTLSDR.git
      dest: /home/{{ ham_user }}/hamradio/SoapyRTLSDR
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory SoapyRTLSDR/build
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyRTLSDR/build
      state: directory

  - name: Build SoapyRTLSDR CMakeFiles
    command: cmake --prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyRTLSDR/build

  - name: Build SoapyRTLSDR
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyRTLSDR/build

  - name: Install SoapyRTLSDR
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyRTLSDR/build

  - name: Remove SoapyRTLSDR build directory
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyRTLSDR
      state: absent
