#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Chromium Bookmarks
  hosts: all
  gather_facts: no
  tasks:

  - name: Include needed variables
    include_vars:
      file: ../default/main.yml

  - name: Create directory chromium
    file:
      path: /home/{{ ham_user }}/.config/chromium/Default
      state: directory

  - name: Copy initial Chromium Bookmarks
    become: yes
    copy:
      src: "{{ playbook_dir }}/../files/Bookmarks"
      dest: "/home/{{ ham_user }}/.config/chromium/Default/Bookmarks"
