#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyAirSpy
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: /home/{{ ham_user }}/hamradio/
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - gr-osmosdr
      - libfftw3-dev
      - libusb-1.0-0-dev
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Download latest SoapyAirSpy sources
    git:
      repo: https://github.com/pothosware/SoapyAirSpy.git
      dest: /home/{{ ham_user }}/hamradio/SoapyAirSpy
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Create directory SoapyAirSpy/build
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyAirSpy/build
      state: directory

  - name: Build SoapyAirSpy CMakeFiles
    command: cmake --prefix=/usr ..
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyAirSpy/build

  - name: Build SoapyAirSpy
    command: make
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyAirSpy/build

  - name: Install SoapyAirSpy
    become: yes
    command: make install
    args:
      chdir: /home/{{ ham_user }}/hamradio/SoapyAirSpy/build

  - name: Remove SoapyAirSpy build directory
    file:
      path: /home/{{ ham_user }}/hamradio/SoapyAirSpy
      state: absent
