#
# Copyright 2020 - 2023, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install D-Rats
  hosts: all
  gather_facts: no
  tasks:

  - name: Download D-Rats sources from John and Maurizio's GitHub
    git:
      repo: https://github.com/ham-radio-software/D-Rats.git
      dest: /home/{{ ham_user }}/hamradio/D-Rats
    retries: 5
    delay: 30
    register: result
    until: result.failed == false

  - name: Modify categories for d-rats.desktop
    become: yes
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/D-Rats/share/d-rats.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio D-Rats

  - name: Modify categories for d-rats_repeater.desktop
    become: yes
    lineinfile:
      path: /home/{{ ham_user }}/hamradio/D-Rats/share/d-rats_repeater.desktop
      regexp: '^Categories=.*'
      line: Categories=HamRadio D-Rats

  - name: Copy D-Rats desktop file
    become: yes
    copy:
      src: "/home/{{ ham_user }}/hamradio/D-Rats/share/d-rats.desktop"
      dest: "/usr/local/share/applications/d-rats.desktop"
      remote_src: yes

  - name: Copy D-Rats Repeater desktop file
    become: yes
    copy:
      src: "/home/{{ ham_user }}/hamradio/D-Rats/share/d-rats_repeater.desktop"
      dest: "/usr/local/share/applications/d-rats_repeater.desktop"
      remote_src: yes
